name: Build and Push Docker Image

# Allow the workflow to be triggered by push or manually with workflow_dispatch
on:
  push:
    branches:
      - main  # Run the workflow when pushing to the main branch
  workflow_dispatch:
    inputs:
      GUILE_VERSION:
        description: 'Version of Guile to build'
        required: true
        default: '3.0.10'  # Default Guile version, you can modify this if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx for building images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to DockerHub using secrets
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the Docker image with dynamic Guile version
      - name: Build Docker image
        run: |
          docker build \
            --build-arg GUILE_VERSION=${{ github.event.inputs.GUILE_VERSION }} \  # Pass the input parameter
            -t ${{ secrets.DOCKERHUB_USERNAME }}/guile:${{ github.event.inputs.GUILE_VERSION }} .  # Tag image with Guile version

      # Push the Docker image to DockerHub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/guile:${{ github.event.inputs.GUILE_VERSION }}  # Push image with the Guile version tag
          
      # Optionally, tag and push the latest version if on main branch
      - name: Tag and push latest version
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/guile:${{ github.event.inputs.GUILE_VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/guile:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/guile:latest
